include: package:lints/recommended.yaml
analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables