name: pathfinder_athenaeum
description: A Flutter rewrite of the Pathfinder Open Reference app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  _fe_analyzer_shared: ^86.0.0
  analyzer: ^8.0.0
  build: ^3.0.0
  build_resolvers: ^3.0.0
  build_runner: ^2.6.0
  build_runner_core: ^9.2.0
  characters: ^1.4.1
  leak_tracker: ^11.0.1
  leak_tracker_flutter_testing: ^3.0.10
  leak_tracker_testing: ^3.0.2
  material_color_utilities: ^0.13.0
  meta: ^1.17.0
  source_gen: ^3.0.0
  test_api: ^0.7.6
  vector_math: ^2.2.0
  vm_service: ^15.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/databases/