name: pathfinder_athenaeum
description: A Flutter rewrite of Pathfinder Open Reference
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  provider: ^6.1.1
  go_router: ^14.2.0
  flutter_html: ^3.0.0
  shared_preferences: ^2.2.2
  sqflite_common_ffi: ^2.3.3
  url_launcher: ^6.3.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/book-apg.db
    - assets/book-arg.db
    - assets/book-b1.db
    - assets/book-b2.db
    - assets/book-b3.db
    - assets/book-b4.db
    - assets/book-cr.db
    - assets/book-gmg.db
    - assets/book-ma.db
    - assets/book-mc.db
    - assets/book-npc.db
    - assets/book-tech.db
    - assets/book-uc.db
    - assets/book-ucampaign.db
    - assets/book-ue.db
    - assets/book-um.db

analysis_options:
  linter:
    rules:
      avoid_print: false