name: pathfinder_athenaeum
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.3
  path_provider: ^2.1.4
  path: ^1.9.0
  go_router: ^15.2.4
  flutter_html: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/book-apg.db
    - assets/book-arg.db
    - assets/book-b1.db
    - assets/book-b2.db
    - assets/book-b3.db
    - assets/book-b4.db
    - assets/book-cr.db
    - assets/book-gmg.db
    - assets/book-ma.db
    - assets/book-mc.db
    - assets/book-npc.db
    - assets/book-tech.db
    - assets/book-uc.db
    - assets/book-ucampaign.db
    - assets/book-ue.db
    - assets/book-um.db