name: pathfinder_athenaeum
description: A Flutter app for Pathfinder reference.
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  path: ^1.9.0
  mockito: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.9
  sqflite_common_ffi: ^2.3.3
  analyzer: ^7.5.6
  characters: ^1.4.1
  leak_tracker: ^11.0.1
  leak_tracker_flutter_testing: ^3.0.10
  leak_tracker_testing: 3.0.1
  material_color_utilities: 0.11.1
  meta: 1.16.0
  test_api: 0.7.4
  vector_math: 2.1.4
  vm_service: 15.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/databases/book-acg.db
    - assets/databases/book-apg.db
    - assets/databases/book-arg.db
    - assets/databases/book-b1.db
    - assets/databases/book-b2.db
    - assets/databases/book-b3.db
    - assets/databases/book-b4.db
    - assets/databases/book-cr.db
    - assets/databases/book-gmg.db
    - assets/databases/book-ma.db
    - assets/databases/book-mc.db
    - assets/databases/book-npc.db
    - assets/databases/book-oa.db
    - assets/databases/book-ogl.db
    - assets/databases/book-pfu.db
    - assets/databases/book-tech.db
    - assets/databases/book-uc.db
    - assets/databases/book-ucampaign.db
    - assets/databases/book-ue.db
    - assets/databases/book-um.db
    - assets/databases/index.db