name: pathfinder_athenaeum
description: A Flutter rewrite of the Pathfinder Open Reference app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.5
  shared_preferences: ^2.2.3
  sqflite_common_ffi: ^2.3.3
  _fe_analyzer_shared: ^85.0.0
  analyzer: ^7.7.0
  build: ^3.0.0
  build_resolvers: ^3.0.0
  build_runner: ^2.4.6
  build_runner_core: ^9.2.0
  characters: ^1.3.0
  leak_tracker: ^10.0.0
  leak_tracker_flutter_testing: ^3.0.9
  leak_tracker_testing: ^3.0.1
  material_color_utilities: ^0.11.1
  meta: ^1.12.0
  source_gen: ^3.0.0
  test_api: 0.7.4
  vector_math: 2.1.4
  vm_service: 15.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/databases/