# Existing content from your pubspec.yaml (based on commit acf15ede)
name: pathfinder_athenaeum
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  sqflite: ^2.3.3+1
  path: ^1.8.3
  synchronized: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  sqflite_common_ffi: ^2.3.3
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/databases/book-cr.db