name: pathfinder_athenaeum
description: A Flutter rewrite of the Pathfinder Open Reference app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  _fe_analyzer_shared: ^85.0.0  # Compatible with older analyzer versions
  analyzer: ^7.7.0           # Matches _fe_analyzer_shared
  build: ^3.0.0              # Stable build version
  build_resolvers: ^3.0.0    # Aligned with build
  build_runner: ^2.4.6       # Compatible with build tools
  build_runner_core: ^9.2.0  # Matches build_runner
  characters: ^1.3.0         # Common SDK version
  leak_tracker: ^10.0.0      # Compatible with test_api
  leak_tracker_flutter_testing: ^3.0.9  # Matches leak_tracker
  leak_tracker_testing: ^3.0.1          # Matches leak_tracker
  material_color_utilities: ^0.11.1      # SDK-compatible
  meta: ^1.12.0             # Widely compatible
  source_gen: ^3.0.0        # Matches build_runner
  test_api: 0.7.4           # Fixed to match flutter_test
  vector_math: ^2.1.4       # Stable version
  vm_service: ^15.0.0       # Common SDK version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/databases/