name: pathfinder_athenaeum
description: A Flutter app replicating Pathfinder Open Reference.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite_common_ffi: ^2.3.3
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/databases/book-cr.db